### PR TITLE
remove groupvar 

### PR DESCRIPTION
**Pull request by fionarhuang**

### CODE REVIEW

**Comment by csoneson** [comment]
Thanks @fionarhuang . I think we need also `pandoc-citeproc` (and we can remove the installation of these two from the travis file to see if it's working from the environment filse)

**Comment by fionarhuang** [comment]
> Thanks @fionarhuang . I think we need also `pandoc-citeproc` (and we can remove the installation of these two from the travis file to see if it's working from the environment filse)

Does that mean I should remove the last commit about adding the pandoc in the environment?

**Comment by csoneson** [comment]
No, just make another commit adding `pandoc-citeproc` and fixing the travis file, and we'll see how it goes on travis

**Comment by fionarhuang** [comment]
> No, just make another commit adding `pandoc-citeproc` and fixing the travis file, and we'll see how it goes on travis

ah... I see.

**Pull request merged**
